#!/bin/bash

#
# alice/payload -- by Dario Berzano <dario.berzano@cern.ch>
#
# Part of virtual-analysis-facility.
#
# Generates the payload (on stdout) to carry to the VAF nodes for ALICE. It is
# currently used to distribute user's Grid proxy onto the nodes.
#

echo "GridProxyBase64=`cat /tmp/x509up_u$UID | gzip -9 | base64`"
